require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)

newoption {
	trigger = "BoostIncPath",
	description = "The Path will be used to refer for boost include files"
}

newoption {
	trigger = "BoostLibPath",
	description = "The path of the boost library files"
}

workspace "TruthEngine"
	architecture "x64"
	startproject "TruthEngine.Editor"

	configurations{
		"Debug",
		"Release",
		"Dist"
	}
	

	flags{
		"MultiProcessorCompile"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

IncludeDir = {}
IncludeDir["TruthEngine.Core"] 		= 	"%{wks.location}/TruthEngine.Core/src"
IncludeDir["TruthEngine.Editor"] 	= 	"%{wks.location}/TruthEngine.Editor/src"
IncludeDir["Dependencies"] 			= 	"%{wks.location}/Dependencies"
IncludeDir["spdlog"] 				= 	"%{wks.location}/Dependencies/spdlog/include"
IncludeDir["imgui"] 				= 	"%{wks.location}/Dependencies/imgui"
IncludeDir["d3dx12"] 				= 	"%{wks.location}/Dependencies/DirectXGraphicsSamples/Libraries/D3DX12"
IncludeDir["physx"] 				= 	"%{wks.location}/Dependencies/Physx"
IncludeDir["boostIncPath"]          =   _OPTIONS["BoostIncPath"]
IncludeDir["boostLibPath"]          =   _OPTIONS["BoostLibPath"]


libdirs 
{ 
	"%{wks.location}/Dependencies/Lib",
	IncludeDir["boostLibPath"]
}

links
{
	"PhysX_static_64.lib",
	"PhysXCharacterKinematic_static_64.lib",
	"PhysXCommon_static_64.lib",
	"PhysXCooking_static_64.lib",
	"PhysXExtensions_static_64.lib",
	"PhysXFoundation_static_64.lib",
	"PhysXPvdSDK_static_64.lib",
	"PhysXVehicle_static_64.lib",
	"DirectXMesh.lib"
}


filter "configurations:Debug"
		libdirs
		{
			"%{wks.location}/Dependencies/Lib/Debug"
		}
		links
		{
			"assimp-vc142-mtd.lib"
		}
		defines{
			"_DEBUG",
			"TE_ENABLE_ASSERTS",
		}


filter "configurations:Release"
	libdirs
		{
			"%{wks.location}/Dependencies/Lib/Release"
		}		
		links
		{
			"assimp-vc142-mt.lib"
		}
		defines{
			"NDEBUG",			
		}


filter "configurations:Dist"
	libdirs
		{
			"%{wks.location}/Dependencies/Lib/Release"
		}	
		links
		{
			"assimp-vc142-mt.lib"
		}
		defines{
			"NDEBUG",			
		}
filter{}


include "TruthEngine.Core"
include "TruthEngine.Editor"
include "Dependencies"


	