require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)

workspace "TruthEngine"
	architecture "x64"
	startproject "TruthEngine.Editor"

	configurations{
		"Debug",
		"Release",
		"Dist"
	}
	

	flags{
		"MultiProcessorCompile"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

IncludeDir = {}
IncludeDir["TruthEngine.Core"] 		= 	"%{wks.location}/TruthEngine.Core/src"
IncludeDir["TruthEngine.Sandbox"] 	= 	"%{wks.location}/TruthEngine.Sandbox/src"
IncludeDir["TruthEngine.Editor"] 	= 	"%{wks.location}/TruthEngine.Editor/src"
IncludeDir["Dependencies"] 			= 	"%{wks.location}/Dependencies"
IncludeDir["spdlog"] 				= 	"%{wks.location}/Dependencies/spdlog/include"
IncludeDir["imgui"] 				= 	"%{wks.location}/Dependencies/imgui"
IncludeDir["d3dx12"] 				= 	"%{wks.location}/Dependencies/DirectXGraphicsSamples/Libraries/D3DX12"
IncludeDir["physx"] 				= 	"%{wks.location}/Dependencies/Physx"


libdirs 
{ 
	"%{wks.location}/Dependencies",
	"%{wks.location}/Dependencies/DirectXShaderCompiler/lib/x64",
	"%{wks.location}/Dependencies/assimp/lib/",
}

links
{
	"PhysX_static_64.lib",
	"PhysXCharacterKinematic_static_64.lib",
	"PhysXCommon_static_64.lib",
	"PhysXCooking_static_64.lib",
	"PhysXExtensions_static_64.lib",
	"PhysXFoundation_static_64.lib",
	"PhysXPvdSDK_static_64.lib",
	"PhysXVehicle_static_64.lib"
}


filter "configurations:Debug"
		libdirs
		{
			"%{wks.location}/Dependencies/GeometryGenerator/lib/x64/Debug",
			"%{wks.location}/Dependencies/Physx/lib/debug",
			"%{wks.location}/Dependencies/assimp/lib/debug",
		}
		links
		{
			"assimp-vc142-mtd.lib"
		}
		defines{
			"_DEBUG",
			"TE_ENABLE_ASSERTS",
		}


filter "configurations:Release"
	libdirs
		{
			"%{wks.location}/Dependencies/GeometryGenerator/lib/x64/Release",
			"%{wks.location}/Dependencies/Physx/lib/release",
			"%{wks.location}/Dependencies/assimp/lib/release",
		}		
		links
		{
			"assimp-vc142-mt.lib"
		}
		defines{
			"NDEBUG",			
		}


filter "configurations:Dist"
	libdirs
		{
			"%{wks.location}/Dependencies/GeometryGenerator/lib/x64/Release",
			"%{wks.location}/Dependencies/Physx/lib/release",
			"%{wks.location}/Dependencies/assimp/lib/release",
		}	
		links
		{
			"assimp-vc142-mt.lib"
		}
		defines{
			"NDEBUG",			
		}
filter{}


include "TruthEngine.Core"
include "TruthEngine.Sandbox"
include "TruthEngine.Editor"
include "Dependencies"


	