require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)

workspace "TruthEngine"
	architecture "x64"
	startproject "TruthEngine.Editor"

	configurations{
		"Debug",
		"Release",
		"Dist"
	}
	

	flags{
		"MultiProcessorCompile"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

IncludeDir = {}
IncludeDir["TruthEngine.Core"] 		= 	"%{wks.location}/TruthEngine.Core/src"
IncludeDir["TruthEngine.Sandbox"] 	= 	"%{wks.location}/TruthEngine.Sandbox/src"
IncludeDir["TruthEngine.Editor"] 	= 	"%{wks.location}/TruthEngine.Editor/src"
IncludeDir["Dependencies"] 			= 	"%{wks.location}/Dependencies"
IncludeDir["spdlog"] 				= 	"%{wks.location}/Dependencies/spdlog/include"
IncludeDir["imgui"] 				= 	"%{wks.location}/Dependencies/imgui"
IncludeDir["d3dx12"] 				= 	"%{wks.location}/Dependencies/DirectXGraphicsSamples/Libraries/D3DX12"


filter ("configurations.Debug")
		defines{
			"TE_ENABLE_ASSERTS",
		}
filter{}


include "TruthEngine.Core"
include "TruthEngine.Sandbox"
include "TruthEngine.Editor"
include "Dependencies"


	