#pragma once

#include "Core/Entity/Components/TagComponent.h"
#include "Core/Entity/Components/TransformComponent.h"
#include "Core/Entity/Components/MeshComponent.h"
#include "Core/Entity/Components/EnvironmentComponent.h"
#include "Core/Entity/Components/BoundingBoxComponent.h"
#include "Core/Entity/Components/MaterialComponent.h"
#include "Core/Entity/Components/ModelComponent.h"
#include "Core/Entity/Components/CameraComponent.h"
#include "Core/Entity/Components/LightComponent.h"
#include "Core/Entity/Components/PhysicsComponent.h"
#include "Core/Entity/Components/SkinnedAnimationComponent.h"
#include "Core/Entity/Components/TranslationComponent.h"
#include "Core/Entity/Components/RotationComponent.h"
#include "Core/Entity/Components/MovementComponent.h"
#include "Core/Entity/Components/UpdatedComponent.h"
